const simplephonisc = [
  ["si", "ki", "a"],
  ["at", "ei", "ee"],
  ["sh", "th", "ch"],
  ["oo", "ee", "ai"],
  ["ou", "ow", "ea"],
  ["ar", "or", "ur"],
  ["ay", "ey", "ow"],
  ["ea", "ie", "ou"],
  ["ie", "ee", "eigh"],
  ["ou", "oi", "oo"],
];

const testRhymics = [
  {"word": "cat", "rhyme": "hat", "option1": "dog", "option2": "car"},
  {"word": "bat", "rhyme": "rat", "option1": "fish", "option2": "ball"},
  {"word": "ball", "rhyme": "hall", "option1": "apple", "option2": "rain"},
  {"word": "dog", "rhyme": "log", "option1": "house", "option2": "bird"},
  {"word": "sun", "rhyme": "fun", "option1": "moon", "option2": "cloud"},
  {"word": "moon", "rhyme": "oon", "option1": "sky", "option2": "sun"},
  {"word": "wind", "rhyme": "kind", "option1": "stone", "option2": "sea"},
  {"word": "star", "rhyme": "car", "option1": "tree", "option2": "sand"},
  {"word": "pen", "rhyme": "ten", "option1": "book", "option2": "pencil"},
  {"word": "rain", "rhyme": "train", "option1": "water", "option2": "cloud"},
  {"word": "light", "rhyme": "fight", "option1": "dark", "option2": "shadow"},
  {"word": "sand", "rhyme": "hand", "option1": "stone", "option2": "rock"},
  {"word": "tree", "rhyme": "bee", "option1": "flower", "option2": "car"},
  {"word": "hat", "rhyme": "bat", "option1": "sock", "option2": "shoe"},
  {"word": "shoe", "rhyme": "too", "option1": "glove", "option2": "ball"},
  {"word": "paper", "rhyme": "taper", "option1": "book", "option2": "pen"},
  {"word": "rainbow", "rhyme": "go", "option1": "cloud", "option2": "sky"},
  {"word": "fire", "rhyme": "hire", "option1": "water", "option2": "wind"},
  {"word": "mouse", "rhyme": "house", "option1": "bird", "option2": "car"},
  {"word": "fish", "rhyme": "dish", "option1": "cat", "option2": "dog"},
  {"word": "book", "rhyme": "look", "option1": "page", "option2": "pen"},
  {"word": "plane", "rhyme": "rain", "option1": "car", "option2": "boat"},
  {
    "word": "apple",
    "rhyme": "chapel",
    "option1": "banana",
    "option2": "orange",
  },
  {"word": "door", "rhyme": "floor", "option1": "window", "option2": "wall"},
  {"word": "ball", "rhyme": "call", "option1": "dog", "option2": "cat"},
  {
    "word": "cheese",
    "rhyme": "please",
    "option1": "bread",
    "option2": "butter",
  },
];

const testAlpha = [
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
  "N",
  "O",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "U",
  "V",
  "W",
  "X",
  "Y",
  "Z",
];
